#!/usr/bin/env ruby
# encoding: utf-8

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')

require 'optparse'
require 'stepper'
require 'stepper/instrument'


options = {
  :si => "step.0",
  :ms => 1,
  :host => "localhost:8082",
  :file => nil 

}


parser = OptionParser.new do |op|
  op.separator "== Step == "
  op.banner = "Usage: Stepper [options]"
  op.separator ""
  op.separator "Register Step => Step을 등록합니다. "

  op.on("-s", "--step-id COLLECTIONSNAME.STEP_ID", "DETERMINE COLLECTION NAME AND STEP ID") do |si|
    options[:si] = si
  end
  
  op.on("-m", "--max-step MAX_STEP", "DETERMINE MAX STEP") do |ms|
    options[:ms] = ms
  end
  

  op.on("-H", "--host HOST", "HOST eg)localhost:8082") do |host|
    options[:host] = host
  end
 
  op.on("-f", "--file PATH", "File path to store actions. The host will be ignored. eg)~/log/stepper.log") do |file|
    options[:file] = file
  end

  op.on("-h", "--help", "I WANT MOAR HALP") do
    puts op
    exit
  end
  
end

parser.parse!

if options[:file]
  File.open(options[:file], "a") do |f|
    f.puts("#{options[:si]}:#{options[:ms]}|s")
    f.close
  end
else
  Stepper.daemon_hostport = options[:host]
  Stepper.step(options[:si],options[:ms])
end
