#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')

require 'optparse'
require 'stepper'
require 'stepper/instrument'


options = {
  :si => "step",
  :cs => 1,
  :host => "localhost:8082"

}


parser = OptionParser.new do |op|
  op.banner = "Usage: Stepper [options]"

  op.separator "Step"
  op.separator ""
  op.separator "Stepping Up"

  op.on("-s", "--step-id STEP_ID", "DETERMINE STEP ID") do |si|
    options[:si] = si
  end
  
  op.on("-u", "--step-up STEP_UP", "HOW MANY STEPS ARE YOU CLIMB?") do |cs|
    options[:cs] = cs
  end
  

  op.on("-H", "--host HOST", "HOST eg)localhost:8082") do |host|
    options[:host] = host
  end
 
  op.on("-h", "--help", "I WANT MOAR HALP") do
    puts op
    exit
  end
  
end

parser.parse!

Stepper.daemon_hostport = options[:host]
Stepper.stepup(options[:si],options[:cs])
