#!/usr/bin/env ruby
# encoding: utf-8

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')

require 'optparse'
require 'stepper'
require 'stepper/instrument'

options = {
  :si => "step",
  :cs => 1,
  :host => "localhost:8082", 
  :file => nil

}

parser = OptionParser.new do |op|
  op.separator "== Stepup == "
  op.banner = "Usage: Steppup [options]"
  op.separator ""
  op.separator "Step up => 이미 등록한  Step을 올립니다."

  op.on("-s", "--step-id STEP_ID", "DETERMINE STEP ID") do |si|
    options[:si] = si
  end
  
  op.on("-u", "--step-up STEP_UP", "HOW MANY STEPS ARE YOU CLIMB?") do |cs|
    options[:cs] = cs
  end 
  

  op.on("-H", "--host HOST", "HOST eg)localhost:8082") do |host|
    options[:host] = host
  end
 
  op.on("-f", "--file PATH", "File path to store actions. The host will be ignored. eg)~/log/stepper.log") do |file|
    options[:file] = file
  end

  op.on("-h", "--help", "I WANT MOAR HALP" ) do
    puts op
    exit
  end
  
end

parser.parse!

if options[:file]
  puts options.to_s
  File.open(options[:file], "a") do |f|
    f.puts("#{options[:si]}:#{options[:cs]}|su")
    f.close
  end
else
  Stepper.daemon_hostport = options[:host]
  Stepper.stepup(options[:si],options[:cs])
end
